In [1]:
import numpy as np
import pandas as pd

arr = np.array([1, 2, 3, 4, 5])
print("NumPy Array:", arr)
print("Type:", type(arr))

s = pd.Series([10, 20, 30, 40, 50])
print("\nPandas Series:\n", s)
print("Type:", type(s))

data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35]}
df = pd.DataFrame(data)
print("\nPandas DataFrame:\n", df)
print("Type:", type(df))

NumPy Array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>

Pandas Series:
 0    10
1    20
2    30
3    40
4    50
dtype: int64
Type: <class 'pandas.core.series.Series'>

Pandas DataFrame:
       Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
Type: <class 'pandas.core.frame.DataFrame'>


# Learning NP

In [2]:
import numpy as np

In [3]:
 a = np.array([[1, 2, 3],
              [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a.shape

(2, 3)

In [5]:
a = np.array([1, 2, 3, 4, 5, 6])
a
a.shape

(6,)

In [6]:
a

array([1, 2, 3, 4, 5, 6])

In [7]:
print(a)

[1 2 3 4 5 6]


In [8]:
a.shape

(6,)

In [9]:
a[2]

np.int64(3)

In [10]:
print(a[3])

4


In [11]:
a[:2]

array([1, 2])

In [12]:
print(a[:2])

[1 2]


In [13]:
a[2:]

array([3, 4, 5, 6])

In [14]:
print(a[::-1])

[6 5 4 3 2 1]


In [17]:
a = np.array(23)
print('No of Dimnesions - ', a.ndim)
print('Shape - ', a.shape)
print('Len of Shape - ', len(a.shape))
print('Size - ', a.size)

No of Dimnesions -  0
Shape -  ()
Len of Shape -  0
Size -  1


In [18]:
a = np.array([1, 2, 3])
print('No of Dimnesions - ', a.ndim)
print('Shape - ', a.shape)
print('Len of Shape - ', len(a.shape))
print('Size - ', a.size)

No of Dimnesions -  1
Shape -  (3,)
Len of Shape -  1
Size -  3


In [19]:
a = np.array([[1, 2, 3],
             [4, 5, 6]])
print('No of Dimnesions - ', a.ndim)
print('Shape - ', a.shape)
print('Len of Shape - ', len(a.shape))
print('Size - ', a.size)

No of Dimnesions -  2
Shape -  (2, 3)
Len of Shape -  2
Size -  6


In [20]:
a = np.array([[[1, 2, 3], 
              [4, 5, 6]],
              [[7, 8, 9],
              [10, 11, 12]]])
print('No of Dimnesions - ', a.ndim)
print('Shape - ', a.shape)
print('Len of Shape - ', len(a.shape))
print('Size - ', a.size)

No of Dimnesions -  3
Shape -  (2, 2, 3)
Len of Shape -  3
Size -  12


In [24]:
b = np.ones(5)
b

array([1., 1., 1., 1., 1.])

In [35]:
c = np.empty((2, 4, 2), dtype='int64')
c

array([[[  23925768161198147,   32370111954616435],
        [  32370051825598556,   12948244072562785],
        [  32651616996819049,   25896170311057512],
        [  28710924373327984,   26740556586287209]],

       [[  27303510834217060,   25896196080664693],
        [  32651591226556520,   12948368627204207],
        [  29555336418492531,   29836540811477108],
        [  30962737072111727, 8389643155844890721]]])

In [36]:
d = np.linspace(2, 10, 5, dtype='int64')
d

array([ 2,  4,  6,  8, 10])

In [29]:
e = np.arange(2, 10, 2)
e

array([2, 4, 6, 8])

In [38]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5, 6])

In [44]:
np.reshape(arr, (2,3), order='F')

array([[0, 2, 4],
       [1, 3, 5]])

In [57]:
e = np.array([10, 1, 8, 2, 6, 3, 4, 9, 5, 7])
np.partition(e, 5)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
np.reshape(e, (10, 1), order='F')

array([[10],
       [ 1],
       [ 8],
       [ 2],
       [ 6],
       [ 3],
       [ 4],
       [ 9],
       [ 5],
       [ 7]])

In [63]:
rng = np.random.default_rng()
rng.integers(2, 9, (3, 2))

array([[2, 4],
       [4, 7],
       [7, 5]])

# Learning PD

In [1]:
import pandas as pd

In [4]:
#Series
data = [1, 2, 3, 4, 5]
index = ['a', 'b', 'c', 'd', 'e']
series = pd.Series(data, index = index)
print(series)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [11]:
#DataFrame
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]], columns=['c0', 'c1', 'c2'], index=['r1', 'r2', 'r3'])
print(df)

    c0  c1  c2
r1   1   2   3
r2   4   5   6
r3   7   8   9


In [ ]:
# to read from a csv file - datafile = pd.read_csv('./filename.csv')
